version: "3.8"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
        githuburl: ${GITHUB_URL}
        nginxport: ${NGINX_PORT} 
        projectname: ${PROJECT_NAME} 
      context: ./
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - laravel:/var/www
    networks:
      - ${PROJECT_NAME}

  db:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    networks:
      - ${PROJECT_NAME}

  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-nginx
    restart: unless-stopped
    ports:
      - ${NGINX_PORT}:80 
    volumes:
      - laravel:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - ${PROJECT_NAME}

  tunnel:
    depends_on:
      - nginx
    container_name: ${PROJECT_NAME}-cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    networks:
      - ${PROJECT_NAME}
    
volumes:
  laravel:
  dbdata:

networks:
  larablog: # Please mention the PROJECT_NAME set in the .env file. default both network and project names are larablog.
    driver: bridge
